# Generated by Django 3.2 on 2022-11-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeegroups_grouppermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPermissions',
        ),
    ]
