# Generated by Django 3.2 on 2022-11-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0002_employee_last_login'),
        ('accounts', '0006_grouppermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeGroups',
            new_name='Employee_Groups',
        ),
        migrations.RenameModel(
            old_name='GroupPermissions',
            new_name='Group_Permissions',
        ),
    ]
