# Generated by Django 3.2 on 2022-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employee_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=185, unique=True),
        ),
    ]
