# Generated by Django 3.2 on 2023-05-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='secundary_color',
            new_name='secondary_color',
        ),
    ]
