# Generated by Django 3.2 on 2023-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_secundary_color_enterprise_secondary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='secondary_color',
        ),
    ]
